### ISSUE TITLE
Could not load 'guard/haml-coffee' or '~/.guard/templates/haml-coffee' or find class Guard::Hamlcoffee

### ISSUE THREAD

**Issue by tommybstitch** [ouvrages/guard-haml-coffee#4]
When trying to initialize haml-coffee into my Guardfile, I get these messages in my terminal

    Could not load 'guard/haml-coffee' or '~/.guard/templates/haml-coffee' or find class Guard::Hamlcoffee
    ERROR - Error is: No such file or directory - /Users/tommybstitch/.guard/templates/haml-coffee

What do I do to get this plugin to work? Thanks!

**Comment by vendethiel** [comment]
Rel: https://github.com/netzpirat/haml-coffee/issues/108#issuecomment-146008270

**Comment by e2** [comment]
Fix is now in officially released guard-haml-coffee gem (v1.0.1).

Enjoy!

**Comment by dodontommy** [comment]
Thanks so much! 

Tommy Bonderenka

Software Developer at backstitch

http://backstit.ch
